/*
 * Step_Motor.c
 *
 *  Created on: Nov 8, 2019
 *      Author: kccistc
 */


#include "Step_Motor.h"

void StepMotorStop()
{
	HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_RESET);
}

void StepMotorCW(uint8_t phase)
{
	switch(phase)
	{
	case 0:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_RESET);
		break;
	case 1:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_RESET);
		break;
	case 2:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_SET);
		break;
	case 3:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_SET);
		break;
	}
}

void StepMotorCCW(uint8_t phase)
{
	switch(phase)
	{
	case 0:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_SET);
		break;
	case 1:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_SET);
		break;
	case 2:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(STEPMOTOR_A1_GPIO, STEPMOTOR_A1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_B1_GPIO, STEPMOTOR_B1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(STEPMOTOR_A2_GPIO, STEPMOTOR_A2_PIN, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(STEPMOTOR_B2_GPIO, STEPMOTOR_B2_PIN, GPIO_PIN_RESET);
		break;
	}
}
